terraform {
  required_providers {
    harness = {
      source = "harness/harness"
    }
  }
}

provider "harness" {
  alias            = "provisioner"
  endpoint         = "https://app.harness.io/gateway"
  account_id       = var.harness_platform_account_id
  platform_api_key = var.harness_platform_api_key
}


variable "harness_platform_projects" {
  default = {
    cristian-terraform-test-org = {
      enable      = true
      description = "Organization generated by terraform harness provider"
      projects = {
        project-test-A = {
          enable      = true
          description = "Project generated by terraform harness provider"
        }
        "project test B" = {
          enable      = true
          description = "Project generated by terraform harness provider"
        }
      }
    }
    default = {
      enable      = true
      description = "Projects generated by terraform harness provider at Account Level"
      projects = {
        "cristian terraform project test" = {
          enable      = true
          description = "Project generated by terraform harness provider"
        }
      }
    }
  }
}

module "bootstrap_project" {
  source                    = "../../harness-project"
  harness_platform_projects = var.harness_platform_projects

  providers = {
    harness = harness.provisioner
  }
}

output "details" {
  value = {
    project = module.bootstrap_project.project
  }
}
