# creates folder
curl -i -X POST \
  'https://app.harness.io/gateway/ng/api/file-store?accountIdentifier=Io9SR1H7TtGBq9LVyJVB2w' \
  -H 'Content-Type: multipart/form-data' \
  -H 'x-api-key: #####' \
  -F identifier="example_folder_filestore_2" \
  -F name="cristian_example" \
  -F type="FOLDER" \
  -F parentIdentifier="Root" \
  -F description="FileStore folder generated by terraform"

# creates file
curl -i -X POST \
  'https://app.harness.io/gateway/ng/api/file-store?accountIdentifier=Io9SR1H7TtGBq9LVyJVB2w' \
  -H 'Content-Type: multipart/form-data' \
  -H 'x-api-key: #####' \
  -F identifier="filestore_1" \
  -F name="example_file_21" \
  -F type="FILE" \
  -F parentIdentifier="example_folder_filestore_2" \
  -F description="FileStore file generated by terraform" \
  -F fileUsage="SCRIPT" \
  -F tags="[]" \
  -F mimeType="txt" \
  -F content=''

# set file content
curl -i -X PUT \
  'https://app.harness.io/gateway/ng/api/file-store/filestore_1?accountIdentifier=Io9SR1H7TtGBq9LVyJVB2w' \
  -H 'Content-Type: multipart/form-data' \
  -H 'x-api-key: #####' \
  -F identifier="filestore_1" \
  -F name="example_file_21" \
  -F type="FILE" \
  -F parentIdentifier="example_folder_filestore_2" \
  -F description="FileStore file generated by terraform" \
  -F fileUsage="SCRIPT" \
  -F tags="[]" \
  -F mimeType="txt" \
  -F content="$(cat .gitignore)"

# curl -s -X GET \
#   'https://app.harness.io/gateway/ng/api/file-store?accountIdentifier=Io9SR1H7TtGBq9LVyJVB2w&identifiers=filese_1' \
#     -H 'x-api-key: #####' | jq  

# check file if not exists
curl -s -X GET \
  'https://app.harness.io/gateway/ng/api/file-store/filese_1?accountIdentifier=Io9SR1H7TtGBq9LVyJVB2w' \
    -H 'x-api-key: #####' | jq .code

# check folder if exists
curl -s -X GET \
  'https://app.harness.io/gateway/ng/api/file-store/example_folder_filestore_2?accountIdentifier=Io9SR1H7TtGBq9LVyJVB2w' \
    -H 'x-api-key: #####' | jq .code

# check folder if not exists
curl -s -X GET \
  'https://app.harness.io/gateway/ng/api/file-store/example_foldertore_2?accountIdentifier=Io9SR1H7TtGBq9LVyJVB2w' \
    -H 'x-api-key: #####' | jq .code

# download file
curl -X GET \
  'https://app.harness.io/gateway/ng/api/file-store/files/filestore_1/download?accountIdentifier=Io9SR1H7TtGBq9LVyJVB2w' \
    -H 'x-api-key: #####'