resource "null_resource" "sanity_delegate_check" {
  for_each = local.delegates

  triggers = {
    delegates = "${each.key}"
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    working_dir = path.root
    command     = <<-EOT

      request=$(curl -s '${var.harness_api_endpoint}/delegate-token-ng/delegate-groups?${each.value.url_args}&delegateTokenName=${each.value.tokenName}' -H 'x-api-key: ${var.harness_platform_api_key}')

      result=$(echo $request | jq '.resource.delegateGroupDetails[].groupName | contains("${each.key}")')

      if [[ $(echo $result) != *true* ]]; then
        # pull delegate file
        curl -X GET \
        '${local.harness_filestore_api}/files/${each.key}_${var.suffix}/download?${each.value.url_args}' \
        -H 'x-api-key: ${var.harness_platform_api_key}' > ${each.value.manifest}
      else
        # generate delegate file
        curl -o ${each.value.manifest} \
          --location \
          --request POST '${each.value.delegate_endpoint}?${each.value.url_args}' \
          --header 'Content-Type: application/json' \
          --header 'x-api-key: ${var.harness_platform_api_key}' --data-raw '${each.value.body}'
      fi
      EOT
  }
}

resource "null_resource" "harness_folder" {
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    working_dir = path.root
    command     = <<-EOT

      request=$(curl -s -X GET '${local.harness_filestore_api}/${local.harness_organization_id}?${local.account_args}' -H 'x-api-key: ${var.harness_platform_api_key}')

      result=$(echo $request | jq '.code')

      if [[ $(echo $result) != *ENTITY_NOT_FOUND* ]]; then
        # create folder
        curl -i -X POST \
        '${local.harness_filestore_api}?${local.account_args}' \
        -H 'Content-Type: multipart/form-data' \
        -H 'x-api-key: ${var.harness_platform_api_key}' \
        -F identifier="${local.harness_organization_id}_${var.suffix}" \
        -F name="${var.harness_organization_id}" \
        -F type="FOLDER" \
        -F parentIdentifier="Root" \
        -F description="FileStore folder generated by terraform"
      fi
      EOT
  }
}

resource "null_resource" "harness_file" {
  depends_on = [
    null_resource.harness_folder
  ]

  for_each = local.delegates

  triggers = {
    delegates = "${each.key}"
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    working_dir = path.root
    command     = <<-EOT

      request=$(curl -s -X GET '${local.harness_filestore_api}/${each.key}_${var.suffix}?${local.account_args}' -H 'x-api-key: ${var.harness_platform_api_key}')

      result=$(echo $request | jq '.code')

      if [[ $(echo $result) != *ENTITY_NOT_FOUND* ]]; then
      curl -i -X POST \
        '${local.harness_filestore_api}?${local.account_args}' \
        -H 'Content-Type: multipart/form-data' \
        -H 'x-api-key: ${var.harness_platform_api_key}' \
        -F identifier="${lower(replace(each.key, "/[\\s-.]/", "_"))}_${var.suffix}" \
        -F name="${each.key}" \
        -F type="FILE" \
        -F parentIdentifier="${local.harness_organization_id}_${var.suffix}" \
        -F description="FileStore file generated by terraform" \
        -F fileUsage="SCRIPT" \
        -F tags="[]" \
        -F mimeType="txt" \
        -F content=''

      curl -i -X PUT \
        '${local.harness_filestore_api}/${each.key}_${var.suffix}?${local.account_args}' \
        -H 'Content-Type: multipart/form-data' \
        -H 'x-api-key: ${var.harness_platform_api_key}' \
        -F identifier="${lower(replace(each.key, "/[\\s-.]/", "_"))}_${var.suffix}" \
        -F name="${each.key}" \
        -F type="FILE" \
        -F parentIdentifier="${local.harness_organization_id}_${var.suffix}" \
        -F description="FileStore file generated by terraform" \
        -F fileUsage="SCRIPT" \
        -F tags="[]" \
        -F mimeType="txt" \
        -F content="$(cat ${each.value.manifest})"
      fi
      EOT
  }
}
